//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     ANTLR Version: 4.13.2
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Generated from Simple.g4 by ANTLR 4.13.2

// Unreachable code detected
#pragma warning disable 0162
// The variable '...' is assigned but its value is never used
#pragma warning disable 0219
// Missing XML comment for publicly visible type or member '...'
#pragma warning disable 1591
// Ambiguous reference in cref attribute
#pragma warning disable 419

using Antlr4.Runtime.Misc;
using IParseTreeListener = Antlr4.Runtime.Tree.IParseTreeListener;
using IToken = Antlr4.Runtime.IToken;

/// <summary>
/// This interface defines a complete listener for a parse tree produced by
/// <see cref="SimpleParser"/>.
/// </summary>
[System.CodeDom.Compiler.GeneratedCode("ANTLR", "4.13.2")]
[System.CLSCompliant(false)]
public interface ISimpleListener : IParseTreeListener {
	/// <summary>
	/// Enter a parse tree produced by <see cref="SimpleParser.program"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterProgram([NotNull] SimpleParser.ProgramContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="SimpleParser.program"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitProgram([NotNull] SimpleParser.ProgramContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="SimpleParser.line"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterLine([NotNull] SimpleParser.LineContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="SimpleParser.line"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitLine([NotNull] SimpleParser.LineContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="SimpleParser.statement"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterStatement([NotNull] SimpleParser.StatementContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="SimpleParser.statement"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitStatement([NotNull] SimpleParser.StatementContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="SimpleParser.variableDeclaration"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterVariableDeclaration([NotNull] SimpleParser.VariableDeclarationContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="SimpleParser.variableDeclaration"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitVariableDeclaration([NotNull] SimpleParser.VariableDeclarationContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="SimpleParser.assignment"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterAssignment([NotNull] SimpleParser.AssignmentContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="SimpleParser.assignment"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitAssignment([NotNull] SimpleParser.AssignmentContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="SimpleParser.functionCall"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterFunctionCall([NotNull] SimpleParser.FunctionCallContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="SimpleParser.functionCall"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitFunctionCall([NotNull] SimpleParser.FunctionCallContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="SimpleParser.ifBlock"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterIfBlock([NotNull] SimpleParser.IfBlockContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="SimpleParser.ifBlock"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitIfBlock([NotNull] SimpleParser.IfBlockContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="SimpleParser.whileBlock"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterWhileBlock([NotNull] SimpleParser.WhileBlockContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="SimpleParser.whileBlock"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitWhileBlock([NotNull] SimpleParser.WhileBlockContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="SimpleParser.forBlock"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterForBlock([NotNull] SimpleParser.ForBlockContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="SimpleParser.forBlock"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitForBlock([NotNull] SimpleParser.ForBlockContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="SimpleParser.forInit"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterForInit([NotNull] SimpleParser.ForInitContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="SimpleParser.forInit"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitForInit([NotNull] SimpleParser.ForInitContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="SimpleParser.forUpdate"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterForUpdate([NotNull] SimpleParser.ForUpdateContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="SimpleParser.forUpdate"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitForUpdate([NotNull] SimpleParser.ForUpdateContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="SimpleParser.variableDeclarationNoSemicolon"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterVariableDeclarationNoSemicolon([NotNull] SimpleParser.VariableDeclarationNoSemicolonContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="SimpleParser.variableDeclarationNoSemicolon"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitVariableDeclarationNoSemicolon([NotNull] SimpleParser.VariableDeclarationNoSemicolonContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="SimpleParser.assignmentNoSemicolon"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterAssignmentNoSemicolon([NotNull] SimpleParser.AssignmentNoSemicolonContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="SimpleParser.assignmentNoSemicolon"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitAssignmentNoSemicolon([NotNull] SimpleParser.AssignmentNoSemicolonContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="SimpleParser.increment"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterIncrement([NotNull] SimpleParser.IncrementContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="SimpleParser.increment"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitIncrement([NotNull] SimpleParser.IncrementContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="SimpleParser.decrement"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterDecrement([NotNull] SimpleParser.DecrementContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="SimpleParser.decrement"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitDecrement([NotNull] SimpleParser.DecrementContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="SimpleParser.functionCallNoSemicolon"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterFunctionCallNoSemicolon([NotNull] SimpleParser.FunctionCallNoSemicolonContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="SimpleParser.functionCallNoSemicolon"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitFunctionCallNoSemicolon([NotNull] SimpleParser.FunctionCallNoSemicolonContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="SimpleParser.block"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterBlock([NotNull] SimpleParser.BlockContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="SimpleParser.block"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitBlock([NotNull] SimpleParser.BlockContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="SimpleParser.argumentList"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterArgumentList([NotNull] SimpleParser.ArgumentListContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="SimpleParser.argumentList"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitArgumentList([NotNull] SimpleParser.ArgumentListContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="SimpleParser.expression"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterExpression([NotNull] SimpleParser.ExpressionContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="SimpleParser.expression"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitExpression([NotNull] SimpleParser.ExpressionContext context);
}
